#! /usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function  # To suppress the space character as well, you can either use
import argparse
import os
from biotldr.SearchCMD import SearchCMD
SUBCMD_CMD = "command"
if __name__ == '__main__':
    ## description - Text to display before the argument help (default: none)
    parser=argparse.ArgumentParser(description='BioTLDR')

    ## Add subcommand
    subparsers = parser.add_subparsers(title='BioTLDR subcommand', 
                                    dest = 'subcommand',
                                    description='Subcommand',
                                    help='XXX')

    parser_cmd = subparsers.add_parser(SUBCMD_CMD, help='Search command line examples.')
    parser_cmd.add_argument('-c', '--command', help='Command', required=True) 
    options = parser.parse_args()
    dict_arg = vars(options)
    print(dict_arg)

    ## This is to get the path of the this file
    exe_folder = os.path.abspath(os.path.dirname(__file__))
    #print dict_arg
    #print("The folder of the path is: %s" % exe_folder)
    if(dict_arg['subcommand']):
        searchCMD = SearchCMD()
        searchCMD.cmd(exe_folder, dict_arg)
    
