#! /usr/bin/env python
# -*- coding: utf-8 -*-
import argparse

class easyNGS:
    def __init__(self):
        """Initiate easyNGS"""

    def cmd(self, subcmd):
        """Find the corresponding md file"""
        print subcmd


if __name__ == '__main__':
    easyNGS = easyNGS()
    ## description - Text to display before the argument help (default: none)
    parser=argparse.ArgumentParser(description='easyNGS')
    parser.add_argument('-c', '--commad', help='Command', required=True) 
    options = parser.parse_args()
    dict_cmd = vars(options)
    print dict_cmd
    #print "Sub command is: " + dict_cmd['command']
    
